#
name: Deploy Shiny App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libcurl4-openssl-dev \
            libpng-dev \
            libgdal-dev \
            libproj-dev \
            libgeos-dev \
            libudunits2-dev
 

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'

      - name: Set up R dependencies
        run: Rscript -e 'install.packages(c("renv", "rsconnect"), repos = "https://cloud.r-project.org")'

      - name: Restore R packages with renv
        run: Rscript -e 'renv::restore()'

      - name: Deploy app to shinyapps.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name=Sys.getenv('SHINYAPPS_NAME'), token=Sys.getenv('SHINYAPPS_TOKEN'), secret=Sys.getenv('SHINYAPPS_SECRET'))"
          Rscript -e "rsconnect::deployApp(appDir = '.', appName = 'feux_qc_shiny', forceUpdate = TRUE)"
