name: Deploy Shiny App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Deploy app to shinyapps.io
        env:
          SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript -e 'install.packages("rsconnect", repos = "https://cloud.r-project.org"); 
                      library(rsconnect); 
                      rsconnect::setAccountInfo(name=Sys.getenv("SHINYAPPS_NAME"), 
                                                token=Sys.getenv("SHINYAPPS_TOKEN"), 
                                                secret=Sys.getenv("SHINYAPPS_SECRET")); 
                      rsconnect::deployApp(appDir = ".", appName = "feux_qc_shiny")'
