name: Deploy Shiny App

on:
  push:
    branches: [ main ]  # Ou "master" si c’est ton nom de branche

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages("rsconnect")
          install.packages(c("shiny", "leaflet", "sf", "dplyr", "shinyWidgets", "ggplot2", "scales", "ggpubr", "tidyr", "readr"))

        shell: Rscript {0}

      - name: Deploy app to shinyapps.io
        env:
          SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          library(rsconnect)
          rsconnect::setAccountInfo(name=Sys.getenv("SHINYAPPS_NAME"),
                                    token=Sys.getenv("SHINYAPPS_TOKEN"),
                                    secret=Sys.getenv("SHINYAPPS_SECRET"))
          rsconnect::deployApp(appDir = ".", appName = "feux_qc_shiny", forceUpdate = TRUE)
        shell: Rscript {0}
