name: Deploy Shiny App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages("rsconnect")
          install.packages(c("shiny", "leaflet", "sf", "dplyr", "shinyWidgets", "ggplot2", "scales", "ggpubr", "tidyr", "readr"))


      - name: Deploy Shiny App to shinyapps.io
        run: |
          install.packages("rsconnect")
          rsconnect::setAccountInfo(name='hgesdrn',
                                    token='${{ secrets.SHINYAPPS_TOKEN }}',
                                    secret='${{ secrets.SHINYAPPS_SECRET }}')
          rsconnect::deployApp(appDir = ".")
