name: Deploy Shiny App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages("rsconnect")
          install.packages(c("shiny", "leaflet", "sf", "dplyr", "shinyWidgets", "ggplot2", "scales", "ggpubr", "tidyr", "readr"))

      - name: Deploy to shinyapps.io
        env:
          RSCONTENT_TOKEN: ${{ secrets.RSCONTENT_TOKEN }}
          RSCONTENT_SECRET: ${{ secrets.RSCONTENT_SECRET }}
        run: |
          library(rsconnect)
          rsconnect::setAccountInfo(
            name='hgesdrn',
            token=Sys.getenv("RSCONTENT_TOKEN"),
            secret=Sys.getenv("RSCONTENT_SECRET")
          )
          rsconnect::deployApp(appDir = ".", appName = "feux_qc_shiny")
