name: Deploy to shinyapps.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      R_LIBS_USER: /home/runner/work/_temp/Library
      TZ: UTC
      NOT_CRAN: true
      SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3.2"

      - name: Install renv and rsconnect manually
        run: |
          install.packages(c("renv", "rsconnect"), repos = "https://cloud.r-project.org")

      - name: Restore packages with renv
        run: |
          Rscript -e 'renv::restore(prompt = FALSE)'

      - name: Deploy app to shinyapps.io
        run: |
          Rscript -e '
            library(rsconnect)
            rsconnect::setAccountInfo(
              name   = Sys.getenv("SHINYAPPS_NAME"),
              token  = Sys.getenv("SHINYAPPS_TOKEN"),
              secret = Sys.getenv("SHINYAPPS_SECRET")
            )
            rsconnect::deployApp(appDir = ".", appName = "feux_qc_shiny", forceUpdate = TRUE)
          '
